In [2]:
# Setup tensorflow
import tensorflow as tf

print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.7.0


In [3]:
# Load a dataset
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()

# Normalization
x_train, x_test = x_train/255.0, x_test/255.0

11501568/11490434 [==============================] - 1s 0us/step


In [5]:
print('x_train',x_train.shape)
print('y_train',y_train.shape)
print('x_test',x_test.shape)
print('y_test',y_test.shape)

x_train (60000, 28, 28)
y_train (60000,)
x_test (10000, 28, 28)
y_test (10000,)


In [4]:
# Build a machine learning model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

2024-02-18 16:33:21.434427: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-02-18 16:33:21.434581: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-02-18 16:33:21.477170: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-02-18 16:33:21.477310: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-02-18 16:33:21.477408: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from S

In [8]:
predictions = model(x_train[:1]).numpy() # predict first data
predictions

2024-02-18 16:41:01.057833: I tensorflow/stream_executor/cuda/cuda_blas.cc:1774] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


array([[ 0.21729031,  0.04674628, -0.11720458, -0.73043525,  0.4062404 ,
        -0.1558819 ,  0.14969908,  0.641702  , -0.25866047, -0.340825  ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.1176475 , 0.09920108, 0.08420026, 0.04560271, 0.1421159 ,
        0.0810058 , 0.10995835, 0.17984664, 0.07309369, 0.06732809]],
      dtype=float32)

The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

In [12]:
# Define a loss function for training using tf.keras.losses.SparseCategoricalCrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.5132346

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 874us/step - loss: 0.2931 - accuracy: 0.9152
Epoch 2/5
1875/1875 [==============================] - 2s 806us/step - loss: 0.1426 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1039 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 2s 983us/step - loss: 0.0858 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0736 - accuracy: 0.9771


In [16]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0736 - accuracy: 0.9778 - 245ms/epoch - 783us/step


[0.07361120730638504, 0.9778000116348267]

In [17]:
probability_model = tf.keras.Sequential([model,
                                        tf.keras.layers.Softmax(),
                                        ])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.05989142e-09, 1.33289380e-10, 2.10286331e-07, 1.79477793e-05,
        7.26787540e-14, 1.60335574e-07, 8.70438297e-14, 9.99981046e-01,
        1.33271271e-07, 5.87386523e-07],
       [2.39864676e-07, 6.24226450e-05, 9.99929309e-01, 3.14649924e-06,
        6.32463442e-14, 3.41458394e-06, 1.07688379e-06, 1.01219302e-11,
        3.54419598e-07, 3.39337979e-15],
       [1.41307908e-07, 9.99327898e-01, 5.58701431e-05, 8.84956444e-06,
        3.03649467e-05, 2.76417040e-06, 7.75560602e-06, 4.48446110e-04,
        1.17146767e-04, 7.59362194e-07],
       [9.99853492e-01, 2.31310815e-09, 4.89970516e-05, 2.80175357e-07,
        8.88587692e-09, 6.54103133e-06, 4.91940682e-07, 7.80374976e-05,
        3.98032540e-07, 1.17383715e-05],
       [6.87133763e-07, 1.50779726e-08, 2.83588997e-05, 7.02956129e-08,
        9.99431670e-01, 3.14223968e-07, 2.36712793e-07, 1.60727999e-04,
        9.23423556e-07, 3.76894197e-04]], dtype=float32)>